package com.bplow.todo.freemark_ex.dao.entity;
// default package
// Generated 2015-7-12 12:19:33 by Hibernate Tools 4.0.0

/**
 * FmFreemarktmpl generated by hbm2java
 */
public class FmFreemarktmpl implements java.io.Serializable {

	private String id;
	private String tmplName;
	private String tmplCnt;

	public FmFreemarktmpl() {
	}

	public FmFreemarktmpl(String id) {
		this.id = id;
	}

	public FmFreemarktmpl(String id, String tmplName, String tmplCnt) {
		this.id = id;
		this.tmplName = tmplName;
		this.tmplCnt = tmplCnt;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getTmplName() {
		return this.tmplName;
	}

	public void setTmplName(String tmplName) {
		this.tmplName = tmplName;
	}

	public String getTmplCnt() {
		return this.tmplCnt;
	}

	public void setTmplCnt(String tmplCnt) {
		this.tmplCnt = tmplCnt;
	}

}
