package com.bplow.todo.freemark_ex.dao.entity;
// default package
// Generated 2015-7-12 12:19:33 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * FmProduct generated by hbm2java
 */
@Entity
@Table(name = "fm_product")
public class FmProduct implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3264910893373557274L;
	
	private Long productId;
	private String productName;
	private String catalogId;
	private String productDesc;
	private String productImageUrl;
	private byte[]  content;
	private Character isShow;
	private Integer orderId;
	private Date gmtCreate;
	private Date gmtModify;
	
	private String contentStr;

	public FmProduct() {
	}

	public FmProduct(String productName, String catalogId, String productDesc,
			String productImageUrl, Character isShow, Integer orderId,
			Date gmtCreate, Date gmtModify) {
		this.productName = productName;
		this.catalogId = catalogId;
		this.productDesc = productDesc;
		this.productImageUrl = productImageUrl;
		this.isShow = isShow;
		this.orderId = orderId;
		this.gmtCreate = gmtCreate;
		this.gmtModify = gmtModify;
	}

	@Id
	@Generated(value=GenerationTime.INSERT)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public Long getProductId() {
		return this.productId;
	}

	public void setProductId(Long productId) {
		this.productId = productId;
	}

	@Column(name="product_name")
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name="catalog_id")
	public String getCatalogId() {
		return this.catalogId;
	}

	public void setCatalogId(String catalogId) {
		this.catalogId = catalogId;
	}

	@Column(name="product_desc")
	public String getProductDesc() {
		return this.productDesc;
	}

	public void setProductDesc(String productDesc) {
		this.productDesc = productDesc;
	}

	@Column(name="product_image_url")
	public String getProductImageUrl() {
		return this.productImageUrl;
	}

	public void setProductImageUrl(String productImageUrl) {
		this.productImageUrl = productImageUrl;
	}
	
	@Lob
	@Basic(fetch = FetchType.LAZY)
	@Column(name = "CONTENT", columnDefinition = "BLOB",nullable=true)
	public byte[] getContent() {
		return content;
	}

	public void setContent(byte[] content) {
		this.content = content;
	}

	@Column(name="is_show")
	public Character getIsShow() {
		return this.isShow;
	}

	public void setIsShow(Character isShow) {
		this.isShow = isShow;
	}

	@Column(name="order_id")
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@Column(name="gmt_create")
	public Date getGmtCreate() {
		return this.gmtCreate;
	}

	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

	@Column(name="gmt_modify")
	public Date getGmtModify() {
		return this.gmtModify;
	}

	public void setGmtModify(Date gmtModify) {
		this.gmtModify = gmtModify;
	}

	@Transient
	public String getContentStr() {
		return contentStr;
	}

	public void setContentStr(String contentStr) {
		this.contentStr = contentStr;
	}

}
